### ISSUE TITLE
crash with select pg_show_plans_disable() when extension not loaded

### ISSUE THREAD

**Issue by legrandlegrand** [cybertec-postgresql/pg_show_plans#12]
postgres=# create extension pg_show_plans;
CREATE EXTENSION
postgres=# select pg_show_plans_disable();
server closed the connection unexpectedly

**Comment by s-hironobu** [comment]
In my environment, it works well.

```
testdb=# create extension pg_show_plans;
CREATE EXTENSION
testdb=# select pg_show_plans_disable();
 pg_show_plans_disable 
-----------------------
 
(1 row)
```

And, I comment out "shared_preload_libraries = 'pg_show_plans' " in the postgresql.conf, the server returns the following message:

```
testdb=# select pg_show_plans_disable();
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

So, I recommend you check your environment.

I will close this issue since your environment is not clear.
Please check your environment and if you still have trouble, create a new issue.
