### ISSUE TITLE
Can we make view pg_show_plans without extension?

### ISSUE THREAD

**Issue by rin-nas** [cybertec-postgresql/pg_show_plans#18]
Hi!
My solution:
```sql
CREATE OR REPLACE FUNCTION json_explain(
    query TEXT,
    params TEXT[] DEFAULT ARRAY[]::text[]
) RETURNS SETOF JSON AS $$
BEGIN
    RETURN QUERY
        EXECUTE 'EXPLAIN ('
                    || ARRAY_TO_STRING(ARRAY_APPEND(params, 'FORMAT JSON'), ',')
                    || ')'
        || query;
END
$$ LANGUAGE plpgsql;

--test
SELECT json_explain('SELECT * FROM pg_class', ARRAY['ANALYSE'])->0;

SELECT json_explain(query)->0, * FROM pg_stat_activity;
```

**Comment by s-hironobu** [comment]
It does not work well.

(1) It cannot support multi-nested level queries, e.g., the SQL functions that involve other queries.

(2) If the user who issues a query changes some configuration parameters, e.g., enable_mergejoin = off and so on, the result of EXPLAIN command shows another plan that is not the same as the user.

(3) Even if you and the user set the same parameters,  it is not sure that you can show the actual plan if the statistics are updated by Vacuum or Analyze commands because PostgreSQL's planner uses the current statistics for planning.
